version: '3'

volumes:
  lupe_postgres:
    external: true

services:
  postgres:
    image: postgres:10
    ports:
    - 5432:5432
    env_file:
    - config.env
    volumes:
    - lupe_postgres:/var/lib/postgresql/data